- name: Send mail
  uses: dawidd6/action-send-mail@v3
  with:
    # Required mail server address:
    server_address: smtp.gmail.com
    # Required mail server port:
    server_port: 465
    # Required mail subject:
    subject: Contact Form Fastest Laps Email
    # Required recipients' addresses:
    to: ptstewari@gmail.com
    # Required sender full name (address can be skipped):
    from: Github Actions # <actions@github.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
    secure: true
    # Optional HTML body read from file:
    html_body: file://index.html
    # Optional unsigned/invalid certificates allowance:
    ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
    convert_markdown: true
    # Optional priority: 'high', 'normal' (default) or 'low'
    priority: normal
